# Generated by Django 2.0.5 on 2018-05-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('momshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='keywords',
            options={'verbose_name': 'Тэг', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='order',
            name='creation_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата создания заказа'),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default=None, max_length=350, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default='', max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=7, verbose_name='Итого'),
        ),
        migrations.AlterField(
            model_name='keywords',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=7, verbose_name='Цена'),
        ),
    ]
