# Generated by Django 2.0.5 on 2018-05-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('momshop', '0003_auto_20180516_1102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carousel',
            options={'verbose_name': 'Баннер', 'verbose_name_plural': 'Баннеры'},
        ),
        migrations.AlterField(
            model_name='products',
            name='models_height',
            field=models.PositiveIntegerField(default=0, verbose_name='Рост модели'),
        ),
    ]
