# Generated by Django 2.0.5 on 2018-05-16 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('momshop', '0004_auto_20180516_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carousel',
            name='name',
        ),
    ]
