# Generated by Django 2.0.5 on 2018-05-16 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('momshop', '0005_remove_carousel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='name',
            field=models.CharField(default=' ', max_length=100, verbose_name='Название'),
        ),
    ]
