# Generated by Django 2.0.5 on 2018-05-17 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('momshop', '0010_order_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='size',
            field=models.CharField(blank=True, max_length=15, verbose_name='Размер'),
        ),
    ]
