# Generated by Django 2.0.5 on 2018-05-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('momshop', '0011_products_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='prev_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=7, verbose_name='Цена без скидки(по желанию)'),
        ),
    ]
