# Generated by Django 2.0.5 on 2018-05-21 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('momshop', '0012_products_prev_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='prev_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Цена без скидки(по желанию)'),
        ),
    ]
