# Generated by Django 2.0.5 on 2018-05-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('momshop', '0013_auto_20180521_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='adress',
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='', max_length=500, verbose_name='Город'),
        ),
    ]
