# Generated by Django 2.0.5 on 2018-05-30 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('momshop', '0015_aboutusdesc_aboutusgallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='', max_length=200, verbose_name='Вопрос')),
                ('answer', models.TextField(default='', verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Вопрос страницы "Инфо"',
                'verbose_name_plural': 'Вопросы страницы "Инфо"',
            },
        ),
        migrations.AlterModelOptions(
            name='aboutusdesc',
            options={'verbose_name': 'Описание на странице "О нас"', 'verbose_name_plural': 'Описание на странице "О нас"'},
        ),
    ]
